### ISSUE TITLE
The spec doesn't mention supporting the Permissions Policy API, though it seems `CH-Save-Data` exists

### ISSUE THREAD

**Issue by summercms** [WICG/savedata#6]
The following comment: https://groups.google.com/a/chromium.org/g/blink-dev/c/HR7tWmewbSA/m/72z32qZSCgAJ

> (5) Add a new permissions policy, CH-Save-Data, which allows Save-Data delegation to be restricted if desired

However, the [spec](https://wicg.github.io/savedata/) doesn't mention supporting the Permissions Policy API.

Would it be a good idea to add a section saying the following:

> ### 6. Policy-controlled features

>
> This document extends the [policy-controlled client hints features](https://wicg.github.io/client-hints-infrastructure/#policy-controlled-client-hints-features) with the following [policy-controlled features](https://w3c.github.io/webappsec-permissions-policy/#policy-controlled-feature):

>
> - `ch-save-data` which has a [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) of `self`

**Comment by arichiv** [comment]
Will do, it should be * though (not self)
