### ISSUE TITLE
Save-Data vs Sec-CH-Save-Data

### ISSUE THREAD

**Issue by bershanskiy** [WICG/savedata#9]
The specification states that the official name of the HTTP header is `Save-Data` while Chromium apparently aims to replace this header with a boolean Structured Header Client Hint named `Sec-CH-Save-Data`. What is the official name of the hint?

Source: https://chromestatus.com/feature/5645928215085056

**Comment by arichiv** [comment]
Sorry for any confusion, I updated the feature. The header `Save-Data` was *not* renamed, but it was made a client hint and a permissions policy `CH-Save-Data` was added. Additionally, it is only sent when some system data saver setting is on (even if the client hint is explicitly requested), unlike other client hints.
